/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ConsolidateAssortmentBatch implements Database.Batchable<SObject>, Database.Stateful {
    global ConsolidateAssortmentBatch(String startedFrom, Set<Id> countryIds, Set<Id> buSourceIds, Set<Id> categoryIds, Set<Id> productIds, Set<Integer> years) {

    }
    global void execute(Database.BatchableContext bc, List<Negoptim__Assortment_Detail__c> scope) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return null;
    }
global class AssortmentConsoWrapper {
}
}
