/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class GridSettingsManager {
    global List<String> ALL_BANNER_FIELDS {
        get;
        set;
    }
    global List<String> ALL_FIELDS {
        get;
        set;
    }
    global List<String> ERRORS {
        get;
        set;
    }
    global List<Negoptim.GridSettingsManager.FilterSettings> FILTERS {
        get;
        set;
    }
    global List<Negoptim.GridSettingsManager.FieldWrapper> GRID_FIELDS {
        get;
        set;
    }
    global Map<String,Map<String,String>> picklistValuesMap {
        get;
        set;
    }
    global List<String> WARNINGS {
        get;
        set;
    }
    global GridSettingsManager(String objectName, String staticFields, String metadataDeveloperName) {

    }
    global GridSettingsManager(String objectName, String staticFields, String metadataDeveloperName, Boolean loadAllFilters) {

    }
    global GridSettingsManager(String objectName, String staticFields, String safeStaticFields, String metadataDeveloperName) {

    }
    global GridSettingsManager(String objectName, String staticFields, String safeStaticFields, String metadataDeveloperName, Boolean loadAllFilters) {

    }
    global GridSettingsManager(String masterObjectName, String masterStaticFields, String objectName, String staticFields, String metadataDeveloperName) {

    }
    global GridSettingsManager(String masterObjectName, String masterStaticFields, String objectName, String staticFields, String metadataDeveloperName, Boolean loadAllFilters) {

    }
    global GridSettingsManager(String masterObjectName, String masterStaticFields, String safeMasterStaticFields, String objectName, String staticFields, String safeStaticFields, String metadataDeveloperName) {

    }
    global GridSettingsManager(String masterObjectName, String masterStaticFields, String safeMasterStaticFields, String objectName, String staticFields, String safeStaticFields, String metadataDeveloperName, Boolean loadAllFilters) {

    }
    global GridSettingsManager(String masterObjectName, String masterStaticFields, String safeMasterStaticFields, String objectName, String staticFields, String safeStaticFields, String metadataDeveloperName, String filter) {

    }
    global GridSettingsManager(String masterObjectName, String masterStaticFields, String safeMasterStaticFields, String objectName, String staticFields, String safeStaticFields, String metadataDeveloperName, String filter, Boolean loadAllFilters) {

    }
    global String buildQuery(List<String> innerQueries, List<String> conditions, String orderBy) {
        return null;
    }
}
