/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RefreshAssortmentClusterBatch implements Database.Batchable<SObject>, Database.Stateful {
    global RefreshAssortmentClusterBatch(String startedFrom, List<Id> assortmentIdList, List<Id> countryOriginIdList, Integer year, List<String> recordTypes) {

    }
    global void execute(Database.BatchableContext bc, List<Negoptim__Assortment_Detail__c> scope) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return null;
    }
}
