/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class NegoptimDate {
    global NegoptimDate() {

    }
    global static Integer convertMonthTextToNumber(String monthName) {
        return null;
    }
    global static Boolean isLeapYear(Integer year) {
        return null;
    }
    global static Date parseDate(String dateValue, String dateFormat) {
        return null;
    }
}
