/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ObjectIterable implements System.Iterator<List<ANY>> {
    global Integer pageNumber {
        get;
        set;
    }
    global Integer setPageSize {
        get;
        set;
    }
    global ObjectIterable(List<Object> lstAccWr) {

    }
    global List<Object> first() {
        return null;
    }
    global Boolean getHasNext() {
        return null;
    }
    global Boolean getHasPrevious() {
        return null;
    }
    global Boolean hasNext() {
        return null;
    }
    global Boolean hasPrevious() {
        return null;
    }
    global List<Object> last() {
        return null;
    }
    global List<Object> next() {
        return null;
    }
    global List<Object> previous() {
        return null;
    }
    global List<Object> setPageSize(Integer pageSize) {
        return null;
    }
}
