/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class NegoptimHelper {
    global NegoptimHelper() {

    }
    global static Boolean checkCreatibility(Schema.SObjectType objType, List<String> fields) {
        return null;
    }
    global static Boolean checkUpdatibility(Schema.SObjectType objType, List<String> fields) {
        return null;
    }
    @AuraEnabled
    global static String getPackagePrefix(Boolean includeUnderscore) {
        return null;
    }
    global static String normalizeAPIName(String name) {
        return null;
    }
}
